Room
gmathi/NovelLibrary pull request #167
Opened 2021-02-09 20:18 UTC by codefionn

This migrates the existing database access solution to Android Room. The only thing that seems to be problematic is the "Restore from Backup" function. Though I did multiple bug fixes on top of that and works fine on my phone, I would keep an eye on it.

I also daily-drived this branch about a month now and it works fine.

2021-02-09 21:15 UTC, codefionn commented
Idea: Restart the app after restoring from backup.

2021-02-10 18:21 UTC, gmathi commented
Holy cow!! This needs a deep detailed review. So it will take some time for me. :)

2021-02-11 15:10 UTC, gmathi requested changes

2021-02-12 13:25 UTC, codefionn commented on app/build.gradle
> +    implementation 'com.google.android.material:material:1.2.1'
Merge error

2021-02-12 13:26 UTC, codefionn reviewed
Yeah, a merge error

2021-02-12 13:32 UTC, codefionn commented
Fixed in #836f1d0

2021-02-17 19:30 UTC, codefionn commented on app/build.gradle
> +    implementation 'com.google.android.material:material:1.2.1'
Fixed by the way

2021-02-17 19:31 UTC, codefionn commented
Discovered a bug: Sometimes chapters aren't marked as read

2021-03-07 04:30 UTC, gmathi approved these changes

2021-03-07 04:30 UTC, merged

2021-03-07 05:00 UTC, gmathi commented
Found an issue. @codefionn In the "Downloads" Screen, Pausing a novel download will remove it from the list. If you relaunch the download screen, it does come back.

2021-03-10 17:47 UTC, codefionn commented
> Found an issue. @codefionn In the "Downloads" Screen, Pausing a novel download will remove it from the list. If you relaunch the download screen, it does come back. 

will try to fix it